#!/usr/bin/env python3

import subprocess
import os
import sys
import json

local_dir = sys.argv[1]

script_input = json.loads(sys.stdin.read())
server = script_input["source"]["server"]
user = script_input["source"].get("user", "concourse-deploy-robot")
remote_dir = script_input["source"]["remote_dir"]
private_key = script_input["source"]["private_key"]
port = script_input["source"].get("port", 22)
rsync_args = script_input["params"].get("rsync_args", [])
path = script_input["params"].get("path", "")

local_dir = os.path.join(local_dir, path)
if not local_dir.endswith("/"):
    local_dir += "/"

if not remote_dir.endswith("/"):
    remote_dir += "/"

subprocess.check_call("mkdir -vp ~/.ssh", shell=True, stdout=sys.stderr)
subprocess.check_call("chmod 600 ~/.ssh", shell=True, stdout=sys.stderr)

home = os.path.expanduser("~")
server_key_file = os.path.join(home, ".ssh/server_key")

with open(server_key_file, "w") as f:
    f.write(private_key)
    if private_key[-1] != "\n":
        f.write("\n")

with open(os.path.join(home, ".ssh/config"), "w") as f:
    f.write("Host {}\n\tStrictHostKeyChecking no\n".format(server))

subprocess.check_call("chmod 600 ~/.ssh/*", shell=True, stdout=sys.stderr)

rsync_cmd = ["rsync", "-Pavz", "-e", "ssh -i {} -p {}".format(server_key_file, port)]
rsync_cmd.extend(rsync_args)
rsync_cmd.extend([local_dir, "{}@{}:{}".format(user, server, remote_dir)])

subprocess.check_call(
    rsync_cmd,
    env={
        "PATH": os.environ["PATH"],
        "SSH_ASKPASS": "/opt/resource/askpass",
        "DISPLAY": "",
    },
    stdout=sys.stderr,
)

resource_version = subprocess.check_output(
    [
        "ssh",
        "-i",
        server_key_file,
        "-p",
        str(port),
        "{}@{}".format(user, server),
        "find {} -exec stat -c %Y {{}} \\; | sort -nr | head -n1".format(remote_dir),
    ],
    env={
        "PATH": os.environ["PATH"],
        "SSH_ASKPASS": "/opt/resource/askpass",
        "DISPLAY": "",
    },
).rstrip()

result = {"version": {"mtime": resource_version.decode("utf8")}}
sys.stdout.write(json.dumps(result))
