#!/usr/bin/env python3

import json
import requests
import sys
import urllib.parse

script_input = json.loads(sys.stdin.read())

uri = script_input["source"].get("uri", "https://event-api.barrucadu.dev")
project = script_input["source"]["project"]

params = {}
if "version" in script_input:
    params = {"since": script_input["version"]["uuid"]}

r = requests.get(f"{uri}/project/{urllib.parse.quote(project)}/events", params=params)
r.raise_for_status()

events = r.json()

out = []
if len(events) > 0:
    if "version" in script_input:
        out = [{"uuid": event["uuid"]} for event in reversed(events)]
    else:
        out = [{"uuid": events[0]["uuid"]}]

print(json.dumps(out))
