#!/usr/bin/env python3

import json
import requests
import sys

script_input = json.loads(sys.stdin.read())

uri = script_input["source"].get("uri", "https://event-api.barrucadu.dev")
project = script_input["source"]["project"]
uuid = script_input["version"]["uuid"]
dest_dir = sys.argv[1]

r = requests.get(f"{uri}/event/{uuid}")
r.raise_for_status()
event = r.json()

with open(f"{dest_dir}/event", "wb") as file:
    file.write(json.dumps(event).encode("utf-8"))

metadata = [{"name": k, "value": v} for k, v in event.items() if k != "project"]
metadata.extend(
    [{"name": f"project_{k}", "value": v} for k, v in event["project"].items()]
)

print(json.dumps({"version": {"uuid": uuid}, "metadata": metadata}))
